"""CSVAT — JWT Authentication Middleware.

Provides a FastAPI dependency that verifies JWT tokens on protected routes.
Controlled by REQUIRE_AUTH setting — when False (default), all requests pass through.
"""

import logging
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import jwt, JWTError
from app.config import get_settings

logger = logging.getLogger(__name__)

settings = get_settings()
_bearer_scheme = HTTPBearer(auto_error=False)


async def verify_token(
    credentials: HTTPAuthorizationCredentials = Depends(_bearer_scheme),
) -> dict | None:
    """Verify JWT token from Authorization header.

    When REQUIRE_AUTH is False (dev mode), this is a no-op.
    When True, requires a valid Bearer token generated by /api/v1/auth/token.

    Returns decoded payload dict, or None if auth is disabled.
    Raises HTTPException 401 if auth is required and token is missing/invalid.
    """
    if not settings.REQUIRE_AUTH:
        return None  # Auth disabled — allow all requests

    if credentials is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required. Get a token from POST /api/v1/auth/token",
            headers={"WWW-Authenticate": "Bearer"},
        )

    token = credentials.credentials
    try:
        payload = jwt.decode(
            token,
            settings.JWT_SECRET_KEY,
            algorithms=[settings.JWT_ALGORITHM],
        )
        return payload
    except JWTError as e:
        logger.warning("JWT verification failed: %s", e)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token. Get a new token from POST /api/v1/auth/token",
            headers={"WWW-Authenticate": "Bearer"},
        )
